version: "3"
services:
  mongodb:
    image: library/mongo
    ports:
      - "27017:27017"
      
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    environment:
      - cluster.name=es-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xmx1g -Xms1g"
      - "discovery.type=single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
  
  # Docs: https://elk-docker.readthedocs.io/
  elk:
    image: sebp/elk
    environment:
      - TZ=America/Sao_Paulo
      - "ES_JAVA_OPTS=-Xmx512m -Xms1g"
    ports:
      - "9201:9200"
      - "9301:9300"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus-config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    network_mode: "host"

  graphana:
    image: grafana/grafana
    ports:
      - 3000:3000
    network_mode: "host"